# Generated by Django 5.1.4 on 2025-02-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
